window.COMMONPLACE_DECK_REGISTRY = window.COMMONPLACE_DECK_REGISTRY || {};
window.COMMONPLACE_DECK_REGISTRY.activedirectory = {
  title: "Active Directory Deck",
  description: "A practical deck covering identity, domain architecture, attack paths, delegation, and common AD administration and security concepts.",
  label: "Active Directory",
  shortLabel: "Active Directory",
  cards: [
    { term: "Forest", definition: "The top-level security boundary containing one or more domains in Active Directory." },
    { term: "Tree", definition: "A set of related AD domains that share a contiguous namespace." },
    { term: "Domain", definition: "A logical grouping of objects managed under a shared directory and authentication boundary." },
    { term: "OU", definition: "An organizational unit used to logically group objects for delegation and policy application." },
    { term: "Trust", definition: "A relationship that allows authentication or resource access across domains or forests." },
    { term: "LDAP", definition: "The protocol used to query and manage directory services such as Active Directory." },
    { term: "LDAPS", definition: "LDAP protected with TLS for encrypted directory communication." },
    { term: "Domain Controller", definition: "A server that stores directory data and handles authentication and policy operations." },
    { term: "Global Catalog", definition: "A partial replica of forest objects used to speed directory searches and logon processes." },
    { term: "FSMO Role", definition: "A specialized Active Directory role assigned to a specific domain controller." },
    { term: "RID Master", definition: "The FSMO role responsible for allocating pools of relative IDs to domain controllers." },
    { term: "PDC Emulator", definition: "An FSMO role that handles time sync, password changes, and legacy compatibility tasks." },
    { term: "Schema Master", definition: "The FSMO role responsible for making changes to the AD schema." },
    { term: "Infrastructure Master", definition: "The FSMO role that updates references to objects in other domains." },
    { term: "Replication", definition: "The process by which domain controllers synchronize directory changes." },
    { term: "SYSVOL", definition: "The shared folder that stores Group Policy and login script data for domain replication." },
    { term: "SPN", definition: "A Service Principal Name used to identify a service instance in Kerberos." },
    { term: "Constrained Delegation", definition: "A delegation model where a service can impersonate users only to specific services." },
    { term: "Unconstrained Delegation", definition: "A risky delegation model where a service can impersonate users broadly." },
    { term: "gMSA", definition: "A group Managed Service Account with automatically managed passwords." },
    { term: "AdminSDHolder", definition: "A protected AD object whose ACL template is applied to privileged accounts and groups." },
    { term: "DCSync", definition: "Abusing directory replication rights to retrieve password data from a domain controller." },
    { term: "ACL", definition: "An access control list that defines which identities can perform actions on an object." },
    { term: "SID", definition: "A security identifier uniquely representing a user, group, or computer object." },
    { term: "Golden Ticket", definition: "A forged Kerberos TGT created with the KRBTGT secret that can grant broad access." },
    { term: "Silver Ticket", definition: "A forged Kerberos service ticket used to access a specific service without contacting a DC." },
    { term: "KRBTGT", definition: "The AD account whose secret is used to sign Kerberos ticket-granting tickets." },
    { term: "RODC", definition: "A Read-Only Domain Controller used in less trusted locations." },
    { term: "Fine-Grained Password Policy", definition: "A password policy applied to selected users or groups instead of an entire domain." },
    { term: "Nested Group", definition: "A group that contains another group as a member." },
    { term: "Inheritance", definition: "The way permissions and policies flow from parent containers to child objects." },
    { term: "AdminCount", definition: "An attribute often associated with protected privileged objects in Active Directory." },
    { term: "Delegation of Control", definition: "Granting limited administrative rights over specific OUs or object sets." },
    { term: "Trust Direction", definition: "Which side of a trust relationship accepts authentication from the other." },
    { term: "Selective Authentication", definition: "A trust setting requiring explicit permission for cross-trust logon to resources." },
    { term: "SID History", definition: "An attribute preserving previous SIDs, sometimes abused for unauthorized access." },
    { term: "LDAP Query", definition: "A request used to search directory objects and their attributes." },
    { term: "AS-REP Roasting", definition: "Requesting Kerberos responses for accounts without preauthentication and cracking them offline." },
    { term: "Domain Functional Level", definition: "The AD feature level available based on supported domain controller versions." },
    { term: "Forest Functional Level", definition: "The forest-wide feature level controlled by the oldest supported DC versions." },
    { term: "Delegated Admin Model", definition: "A planned structure for giving teams only the directory rights they need." },
    { term: "Shadow Credentials", definition: "Abusing certificate-related attributes to create alternative authentication paths for an account." },
    { term: "Certificate Services", definition: "Windows infrastructure used to issue and manage digital certificates." },
    { term: "ESC1", definition: "A common AD CS abuse path involving dangerous enrollment permissions and client authentication templates." },
    { term: "Password Replication Policy", definition: "Rules controlling which credentials can be cached on an RODC." },
    { term: "Replication Metadata", definition: "Directory data showing when an object changed and which DC originated the update." },
    { term: "Authentication Silo", definition: "A mechanism that restricts where privileged accounts can authenticate." },
    { term: "Tiered Administration", definition: "Separating admin roles by system sensitivity to reduce privilege crossover." },
    { term: "Protected Users", definition: "A group that applies stronger authentication protections to selected accounts." },
    { term: "Resource-Based Constrained Delegation", definition: "A delegation model where the target service controls which principals may impersonate to it." }
  ],
};
