window.COMMONPLACE_DECK_REGISTRY = window.COMMONPLACE_DECK_REGISTRY || {};
window.COMMONPLACE_DECK_REGISTRY.ai102 = {
  title: "Microsoft Azure AI-102 Deck",
  description: "A certification-focused deck covering Azure AI services, generative AI concepts, search, vision, language, speech, and responsible AI topics aligned with AI-102 study.",
  label: "Azure AI Engineer",
  shortLabel: "Azure AI-102",
  cards: [
    { term: "Model Deployment", definition: "The process of making a selected AI model available for inference in an Azure AI solution." },
    { term: "Azure AI Foundry", definition: "Microsoft's platform experience for building, evaluating, and managing AI applications and models." },
    { term: "Azure OpenAI Service", definition: "A managed Azure service for accessing OpenAI models with enterprise controls and Azure integration." },
    { term: "Azure AI Services", definition: "A collection of Azure APIs and services for vision, speech, language, decision, and document intelligence scenarios." },
    { term: "Resource Endpoint", definition: "The URL clients use to call an Azure AI service resource." },
    { term: "Key Authentication", definition: "Using an access key to authorize requests to an Azure AI service." },
    { term: "Microsoft Entra Authentication", definition: "Using Azure identity tokens instead of keys to access Azure resources securely." },
    { term: "Custom Subdomain", definition: "A unique endpoint name assigned to an Azure AI resource for secure access and integration." },
    { term: "Responsible AI", definition: "A set of practices for building AI systems that are fair, safe, transparent, and accountable." },
    { term: "Content Filter", definition: "A moderation layer used to detect and block unsafe prompts or model outputs." },
    { term: "Prompt Engineering", definition: "Designing prompts and instructions to improve model behavior and output quality." },
    { term: "System Message", definition: "A high-level instruction that sets behavior and constraints for a chat model." },
    { term: "Grounding", definition: "Providing external facts or source content so model responses stay anchored to relevant data." },
    { term: "RAG", definition: "Retrieval-Augmented Generation, combining search results with generation to improve accuracy and context." },
    { term: "Embeddings", definition: "Vector representations of text used for similarity search, clustering, and semantic retrieval." },
    { term: "Vector Search", definition: "Searching by semantic closeness using vector representations instead of only keyword matching." },
    { term: "Azure AI Search", definition: "A cloud search service that supports indexing, keyword search, semantic ranking, and vector retrieval." },
    { term: "Index Schema", definition: "The field structure that defines what data is stored and searchable in Azure AI Search." },
    { term: "Indexer", definition: "A search component that pulls data from a source and populates a search index." },
    { term: "Skillset", definition: "An enrichment pipeline used in Azure AI Search to extract or generate additional searchable data." },
    { term: "Semantic Ranker", definition: "An Azure AI Search capability that improves relevance using semantic understanding." },
    { term: "Chat Completions", definition: "A conversational API pattern where messages are sent and the model returns a chat-oriented response." },
    { term: "Tokens", definition: "Units of text processed by language models, used for limits, pricing, and generation length." },
    { term: "Temperature", definition: "A parameter controlling output randomness and creativity in generation." },
    { term: "Top-p", definition: "A sampling parameter that limits token selection to the most probable cumulative range." },
    { term: "Document Intelligence", definition: "An Azure AI service for extracting structured data from forms, documents, and invoices." },
    { term: "Prebuilt Model", definition: "A ready-made model for common document types such as receipts or invoices." },
    { term: "Custom Extraction Model", definition: "A trained model used to extract fields from a specific document format." },
    { term: "Read OCR", definition: "Optical character recognition for extracting printed or handwritten text from images or documents." },
    { term: "Azure AI Vision", definition: "A service used for image analysis, OCR, tagging, captioning, and related vision tasks." },
    { term: "Image Captioning", definition: "Generating a human-readable description of image content." },
    { term: "Object Detection", definition: "Identifying and locating objects within an image." },
    { term: "Face Detection", definition: "Locating human faces in an image, often for downstream non-identification use cases." },
    { term: "Azure AI Language", definition: "A service for text analytics, question answering, summarization, and conversational language understanding." },
    { term: "Named Entity Recognition", definition: "Extracting entities such as people, organizations, and locations from text." },
    { term: "Key Phrase Extraction", definition: "Identifying the most important phrases in a document." },
    { term: "Sentiment Analysis", definition: "Determining the emotional tone or polarity of text." },
    { term: "Question Answering", definition: "A feature for returning answers from a curated knowledge source or text base." },
    { term: "Conversational Language Understanding", definition: "A language feature for mapping utterances to intents and entities." },
    { term: "Azure AI Speech", definition: "A service for speech-to-text, text-to-speech, translation, and speaker-related features." },
    { term: "Speech-to-Text", definition: "Transcribing spoken audio into text." },
    { term: "Text-to-Speech", definition: "Generating spoken audio from text input." },
    { term: "Language Detection", definition: "Identifying which language a piece of text is written in." },
    { term: "Translation", definition: "Converting text or speech from one language into another." },
    { term: "Batch Inference", definition: "Running model predictions asynchronously across larger datasets or documents." },
    { term: "Real-Time Inference", definition: "Returning predictions immediately in response to live requests." },
    { term: "Managed Identity", definition: "An Azure identity feature used by services to access other resources without embedded secrets." },
    { term: "Private Endpoint", definition: "A private network path to an Azure service that avoids public internet exposure." },
    { term: "Quota", definition: "A usage or capacity limit applied to an Azure service deployment." },
    { term: "Monitoring", definition: "Tracking service health, latency, failures, and usage through Azure tools like Monitor and logs." },
    { term: "Model Catalog", definition: "The available collection of models and model metadata a practitioner can browse and choose from in Azure AI workflows." },
    { term: "Evaluation Dataset", definition: "A curated set of prompts, ground truth, or examples used to measure model or flow quality." },
    { term: "Prompt Flow", definition: "A structured workflow for designing, testing, and evaluating prompts and model interactions." },
    { term: "Prompt Template", definition: "A reusable prompt pattern with placeholders for variables or injected context." },
    { term: "Model Evaluation", definition: "Assessing model or flow quality against defined metrics, examples, or human review." },
    { term: "Tracing", definition: "Capturing execution details for prompts, tool calls, and model behavior to support debugging and analysis." },
    { term: "Feedback Collection", definition: "Gathering user or evaluator input to improve model quality and system behavior." },
    { term: "Model Reflection", definition: "A technique where a model reviews or critiques its own output to improve results." },
    { term: "Fine-Tuning", definition: "Training a model further on targeted examples to better fit a specific task or style." },
    { term: "Container Deployment", definition: "Running an Azure AI capability in a container for local, offline, or edge scenarios." },
    { term: "Agent Service", definition: "The Microsoft Foundry capability for creating and managing agents that can reason and use tools." },
    { term: "Agent Framework", definition: "A framework used to build more complex agent workflows, orchestration, and autonomy." },
    { term: "Multi-Agent Workflow", definition: "A design where multiple agents collaborate or specialize to complete a larger task." },
    { term: "Azure AI Video Indexer", definition: "A service that extracts searchable insights such as speech, scenes, faces, and topics from video." },
    { term: "Spatial Analysis", definition: "A computer vision capability for understanding movement, presence, and location of people in video." },
    { term: "PII Detection", definition: "Identifying sensitive personal information in text such as names, phone numbers, or identifiers." },
    { term: "SSML", definition: "Speech Synthesis Markup Language, used to control pronunciation, pauses, and speaking style in text-to-speech." },
    { term: "Custom Speech", definition: "A speech capability where models are adapted for specialized vocabulary, accents, or audio conditions." },
    { term: "Keyword Recognition", definition: "Detecting a specific spoken phrase that acts like a trigger or wake word." },
    { term: "Custom Question Answering", definition: "Building a question-answering solution from curated content and question-answer pairs." },
    { term: "Knowledge Base", definition: "A structured store of questions, answers, and sources used for answering user queries." },
    { term: "Chit-Chat", definition: "Predefined conversational responses added to improve user interaction in question-answering systems." },
    { term: "Knowledge Store Projection", definition: "Persisting enriched search pipeline outputs into files, tables, or objects for downstream use." },
    { term: "Custom Skill", definition: "A user-defined enrichment step added to an Azure AI Search skillset." },
    { term: "Composed Model", definition: "A document intelligence model that combines multiple component models for different document types." },
    { term: "Content Understanding", definition: "An Azure capability for extracting and classifying information from documents, images, audio, and video." }
  ],
};
