window.COMMONPLACE_DECK_REGISTRY = window.COMMONPLACE_DECK_REGISTRY || {};
window.COMMONPLACE_DECK_REGISTRY.aws = {
  title: "AWS Security Deck",
  description: "A practical deck covering AWS identity, cloud logging, networking, storage protection, governance, and detection concepts.",
  label: "AWS Security",
  shortLabel: "AWS Security",
  cards: [
    { term: "AWS Account", definition: "A top-level cloud boundary with its own billing, identities, and resources." },
    { term: "Organization", definition: "An AWS structure used to manage multiple accounts centrally." },
    { term: "OU", definition: "An organizational unit within AWS Organizations used to group accounts for governance." },
    { term: "IAM", definition: "AWS Identity and Access Management, used to control identities and permissions." },
    { term: "IAM Role", definition: "A permission-bearing identity intended to be assumed by users, services, or workloads." },
    { term: "IAM Policy", definition: "A JSON document that defines allowed or denied AWS actions and resource scopes." },
    { term: "Least Privilege Policy", definition: "An IAM policy that grants only the exact actions and resources required." },
    { term: "STS", definition: "Security Token Service, used to issue temporary AWS credentials." },
    { term: "AssumeRole", definition: "The process of switching into an IAM role to gain temporary permissions." },
    { term: "CloudTrail", definition: "AWS's audit log of API activity and account events." },
    { term: "CloudWatch", definition: "AWS monitoring used for metrics, logs, alarms, and operational visibility." },
    { term: "GuardDuty", definition: "AWS's threat detection service for suspicious account and workload behavior." },
    { term: "Security Hub", definition: "A centralized AWS service for aggregating findings and security posture data." },
    { term: "Config", definition: "A service that records resource configuration history and evaluates compliance." },
    { term: "S3 Bucket Policy", definition: "A resource policy controlling access to an S3 bucket and its objects." },
    { term: "Block Public Access", definition: "An S3 control that prevents unintended public exposure of buckets and objects." },
    { term: "KMS", definition: "Key Management Service, used to create and manage encryption keys." },
    { term: "VPC", definition: "A Virtual Private Cloud, AWS's isolated networking environment for resources." },
    { term: "Security Group", definition: "A stateful virtual firewall applied to instances and other resources." },
    { term: "NACL", definition: "A network ACL, a stateless packet filter applied at the subnet level." },
    { term: "Private Subnet", definition: "A subnet not directly routable from the internet." },
    { term: "Public Subnet", definition: "A subnet that can route to the internet through an attached gateway." },
    { term: "VPC Flow Logs", definition: "Network metadata logs capturing accepted and rejected traffic in a VPC." },
    { term: "Detective", definition: "An AWS investigation service that helps analyze events, users, and resource behavior." },
    { term: "Control Tower", definition: "An AWS governance service that sets up and enforces multi-account best practices." },
    { term: "Root User", definition: "The highest-privilege identity in an AWS account, meant for very limited use." },
    { term: "Permission Boundary", definition: "A managed policy that limits the maximum permissions an IAM principal can receive." },
    { term: "SCP", definition: "A Service Control Policy used in AWS Organizations to restrict permissions across accounts." },
    { term: "Access Analyzer", definition: "A service that identifies resources shared externally or access patterns that may be risky." },
    { term: "KMS Key Policy", definition: "A resource policy controlling who can use and manage a KMS key." },
    { term: "Secrets Manager", definition: "A service for storing, rotating, and retrieving secrets securely." },
    { term: "Parameter Store", definition: "A configuration and secret storage feature in AWS Systems Manager." },
    { term: "EC2 Instance Profile", definition: "The mechanism that attaches an IAM role to an EC2 instance." },
    { term: "Session Tag", definition: "Metadata attached to a temporary STS session for policy or audit use." },
    { term: "S3 Versioning", definition: "Keeping multiple versions of an object to support recovery and change tracking." },
    { term: "S3 Object Lock", definition: "A protection feature that prevents object deletion or modification for a retention period." },
    { term: "Bucket Encryption", definition: "Using AWS-managed or customer-managed keys to encrypt S3 data at rest." },
    { term: "NAT Gateway", definition: "A managed service allowing private subnet instances to reach the internet outbound." },
    { term: "Transit Gateway", definition: "A hub service used to centrally connect many VPCs and networks." },
    { term: "PrivateLink", definition: "A feature for privately accessing supported services over private IP connectivity." },
    { term: "Inspector", definition: "An AWS service that scans workloads for vulnerabilities and exposure." },
    { term: "Macie", definition: "A data security service focused on discovering and protecting sensitive data in S3." },
    { term: "WAF", definition: "AWS Web Application Firewall used to filter malicious web requests." },
    { term: "Shield", definition: "AWS DDoS protection services for workloads and internet-facing resources." },
    { term: "CloudFormation Drift", definition: "A difference between deployed resource state and the declared infrastructure template." },
    { term: "Lambda Execution Role", definition: "The IAM role used by a Lambda function when it runs." },
    { term: "AssumeRole Policy", definition: "The trust policy that defines who is allowed to assume an IAM role." },
    { term: "Security Lake", definition: "An AWS service for centralizing security data in a normalized format." },
    { term: "Delegated Administrator", definition: "An account authorized to manage a service across an AWS Organization." },
    { term: "AWS Backup Vault", definition: "A logical container used to store and protect backup recovery points in AWS." }
  ],
};
