window.COMMONPLACE_DECK_REGISTRY = window.COMMONPLACE_DECK_REGISTRY || {};
window.COMMONPLACE_DECK_REGISTRY.azure = {
  title: "Azure Security Deck",
  description: "A cloud-focused deck covering Azure identity, resource security, networking, monitoring, and governance concepts.",
  label: "Azure Security",
  shortLabel: "Azure Security",
  cards: [
    { term: "Microsoft Entra ID", definition: "The identity and access service formerly known as Azure Active Directory." },
    { term: "Tenant", definition: "An Azure directory boundary representing an organization's identity environment." },
    { term: "Subscription", definition: "A billing and resource container used to organize Azure services." },
    { term: "Management Group", definition: "A governance layer above subscriptions used to apply policies and organization-wide structure." },
    { term: "Resource Group", definition: "A logical container for Azure resources that share lifecycle or management needs." },
    { term: "RBAC", definition: "Role-based access control used to assign Azure permissions through roles and scopes." },
    { term: "PIM", definition: "Privileged Identity Management, used to govern just-in-time privileged role activation." },
    { term: "Conditional Access", definition: "Policy logic that decides whether and how identities can sign in based on conditions." },
    { term: "Managed Identity", definition: "An automatically managed service identity used by Azure resources." },
    { term: "Service Principal", definition: "An application identity used to access Azure resources programmatically." },
    { term: "Key Vault", definition: "An Azure service for storing secrets, keys, and certificates securely." },
    { term: "NSG", definition: "A Network Security Group used to allow or deny traffic to Azure resources." },
    { term: "VNet", definition: "A virtual network used to isolate and route Azure resources." },
    { term: "Private Endpoint", definition: "A private IP-based path for reaching Azure services without public exposure." },
    { term: "Defender for Cloud", definition: "Azure's cloud security posture and workload protection platform." },
    { term: "Azure Policy", definition: "A governance service used to audit or enforce resource configuration rules." },
    { term: "Blueprint", definition: "A packaged governance model for deploying policies, roles, and resource templates together." },
    { term: "Sentinel", definition: "Microsoft's cloud-native SIEM and SOAR platform." },
    { term: "Log Analytics Workspace", definition: "A data store used by Azure Monitor and Sentinel for collected telemetry." },
    { term: "KQL", definition: "Kusto Query Language, used to search and analyze Azure and Sentinel data." },
    { term: "Storage Account", definition: "A scalable Azure service for blobs, files, queues, and tables." },
    { term: "Shared Access Signature", definition: "A token granting delegated temporary access to storage resources." },
    { term: "Azure Firewall", definition: "A managed network firewall service for filtering Azure traffic." },
    { term: "Application Gateway WAF", definition: "A web application firewall capability built into Azure Application Gateway." },
    { term: "Security Default", definition: "A baseline identity security configuration provided by Microsoft for Entra tenants." },
    { term: "Defender for Identity", definition: "A Microsoft detection service focused on identity threats and suspicious directory activity." },
    { term: "Defender for Endpoint", definition: "Microsoft's endpoint protection and detection platform, often integrated with Azure security tooling." },
    { term: "Azure Monitor", definition: "A platform for metrics, logs, alerts, and visibility across Azure resources." },
    { term: "Azure Activity Log", definition: "A record of control-plane operations performed against Azure resources." },
    { term: "Diagnostic Settings", definition: "Configuration that sends Azure logs and metrics to destinations such as Log Analytics." },
    { term: "Managed HSM", definition: "A dedicated Azure key management service for higher-assurance cryptographic operations." },
    { term: "Azure Bastion", definition: "A managed service for securely reaching Azure VMs without exposing RDP or SSH publicly." },
    { term: "Azure Arc", definition: "A service used to extend Azure management and policy to non-Azure resources." },
    { term: "Blueprint Assignment", definition: "Applying a packaged governance configuration to a specific Azure scope." },
    { term: "Landing Zone", definition: "A preconfigured Azure environment built with governance, identity, and networking foundations." },
    { term: "Deny Assignment", definition: "A protection mechanism that explicitly blocks certain actions at a scope." },
    { term: "Custom Role", definition: "A user-defined Azure RBAC role containing selected allowed actions." },
    { term: "Subscription Inheritance", definition: "The way policies and permissions flow from higher Azure scopes into subscriptions." },
    { term: "Privileged Access Group", definition: "A group whose membership grants elevated access and is often managed with approvals or time limits." },
    { term: "Entra App Registration", definition: "The identity definition for an application integrated with Microsoft Entra ID." },
    { term: "Enterprise Application", definition: "The service principal representation of an app within a tenant." },
    { term: "Federated Credential", definition: "A trust-based identity link that can replace long-lived secrets in workload authentication." },
    { term: "Azure DNS Zone", definition: "A hosted DNS namespace managed within Azure." },
    { term: "ExpressRoute", definition: "A private dedicated connectivity option between on-premises environments and Microsoft cloud services." },
    { term: "Azure Front Door", definition: "A global entry service for application delivery, routing, and protection." },
    { term: "Data Exfiltration Protection", definition: "Controls designed to prevent Azure resources from sending data to unauthorized destinations." },
    { term: "Resource Lock", definition: "A protection setting that helps prevent accidental deletion or modification of Azure resources." },
    { term: "Azure Disk Encryption", definition: "Encryption of VM disks using Azure-managed or customer-managed keys." },
    { term: "Sentinel Analytic Rule", definition: "A detection rule in Microsoft Sentinel that creates incidents or alerts from log queries." },
    { term: "User-Assigned Managed Identity", definition: "A standalone managed identity that can be attached to multiple Azure resources." }
  ],
};
