window.COMMONPLACE_DECK_REGISTRY = window.COMMONPLACE_DECK_REGISTRY || {};
window.COMMONPLACE_DECK_REGISTRY.blueteam = {
  title: "Blue Team Deck",
  description: "A defensive operations deck covering detection strategy, telemetry quality, investigations, and hardening concepts.",
  label: "Blue Team Ops",
  shortLabel: "Blue Team",
  cards: [
    { term: "Detection Tuning", definition: "Adjusting logic to reduce noise while preserving detection value." },
    { term: "Coverage Gap", definition: "An area where malicious activity would be difficult to detect due to missing visibility or logic." },
    { term: "Signal-to-Noise Ratio", definition: "A measure of how much meaningful security signal exists compared with alert clutter." },
    { term: "Hunt Hypothesis", definition: "A testable theory about suspicious behavior to investigate proactively." },
    { term: "Entity Analytics", definition: "Behavioral analysis focused on users, hosts, accounts, or services as tracked entities." },
    { term: "UEBA", definition: "User and Entity Behavior Analytics, which looks for anomalous patterns across identities and systems." },
    { term: "Detection-as-Code", definition: "Managing detections in version-controlled files rather than ad hoc UI edits." },
    { term: "Alert Fidelity", definition: "How often an alert points to truly relevant or malicious activity." },
    { term: "Hardened Baseline", definition: "A standard secure configuration applied consistently across systems." },
    { term: "Allow List Drift", definition: "The gradual expansion of exceptions until controls become ineffective." },
    { term: "Telemetry Normalization", definition: "Transforming different log formats into a consistent searchable schema." },
    { term: "Use Case Lifecycle", definition: "The stages of designing, testing, deploying, tuning, and retiring detections." },
    { term: "Atomic Test", definition: "A small controlled test of a single technique used to validate detections." },
    { term: "Canary", definition: "A deceptive signal or object that should rarely be touched and can generate high-confidence alerts." },
    { term: "Deception Technology", definition: "Defensive tooling that deploys decoys or traps to identify adversary activity." },
    { term: "Mean Time to Detect", definition: "The average time between malicious activity starting and defenders identifying it." },
    { term: "Mean Time to Respond", definition: "The average time between detection and effective response action." },
    { term: "Containment Scope", definition: "The systems, accounts, or segments that need to be restricted to control an incident." },
    { term: "Triage Queue Health", definition: "A measure of whether incoming alert load is staying manageable for analysts." },
    { term: "Detection Validation", definition: "Confirming that a rule fires when expected and supports investigation." },
    { term: "Hardening Exception", definition: "A documented deviation from a security standard that introduces some risk." },
    { term: "Analyst Escalation Path", definition: "The defined route for moving difficult cases to more specialized responders." },
    { term: "Threat-Informed Defense", definition: "Defensive planning guided by realistic adversary tradecraft and observed attack paths." },
    { term: "Environmental Noise", definition: "Background activity unique to an organization that can distort generic detections." },
    { term: "Responder Playbook", definition: "A documented sequence of decisions and actions for a specific incident type." },
    { term: "Detection Gap Analysis", definition: "A review of what attack behaviors lack adequate visibility or rules." },
    { term: "Log Retention", definition: "How long security and operational logs are stored and searchable." },
    { term: "Investigation Pivot", definition: "Switching an investigation from one artifact or entity to another related clue." },
    { term: "Case Enrichment", definition: "Adding internal or external context to make a case easier to interpret." },
    { term: "Entity Resolution", definition: "Linking different records that refer to the same user, host, service, or device." },
    { term: "Suppression Rule", definition: "Logic used to silence known-benign alerts under controlled circumstances." },
    { term: "Detection Drift", definition: "The gradual decline in a rule's effectiveness as environments or attacker behavior change." },
    { term: "Analyst Fatigue", definition: "Reduced effectiveness caused by high alert volume, repetitive tasks, or constant interruptions." },
    { term: "Case Severity Calibration", definition: "Adjusting severity assignments so they better reflect actual business and security impact." },
    { term: "Data Loss Monitoring", definition: "Watching for suspicious movement or copying of sensitive information." },
    { term: "Centralized Logging", definition: "Collecting logs from many systems into one searchable platform." },
    { term: "Cross-Source Correlation", definition: "Connecting related events from different tools or log sources." },
    { term: "Containment Verification", definition: "Checking whether response actions actually stopped the malicious behavior." },
    { term: "Recovery Validation", definition: "Confirming restored systems are trustworthy and functioning after an incident." },
    { term: "High-Confidence Alert", definition: "An alert type with strong evidence and low expected false-positive rate." },
    { term: "Low-and-Slow Activity", definition: "Malicious behavior spread out over time to reduce visibility." },
    { term: "Defensive Depth", definition: "Using multiple overlapping controls so one missed detection does not become a full failure." },
    { term: "Change Window Awareness", definition: "Knowing planned admin activity so analysts do not confuse it with malicious behavior." },
    { term: "Case Ownership", definition: "Clear assignment of who is responsible for progressing and closing a case." },
    { term: "Escalation Criteria", definition: "The conditions that determine when a case should be handed off or raised in severity." },
    { term: "Artifact Collection Plan", definition: "A defined list of data sources and evidence to gather during response." },
    { term: "Detection Backtesting", definition: "Running new rules against historical data to measure usefulness and noise." },
    { term: "Coverage Mapping", definition: "Aligning detections against techniques, assets, or risks to understand protection level." },
    { term: "SOC Workflow Automation", definition: "Using scripts or orchestration tools to reduce repetitive analyst tasks." },
    { term: "Investigation Narrative", definition: "A coherent explanation of what happened, how it was discovered, and what it means." }
  ],
};
