window.COMMONPLACE_DECK_REGISTRY = window.COMMONPLACE_DECK_REGISTRY || {};
window.COMMONPLACE_DECK_REGISTRY.bugbounty = {
  title: "Bug Bounty Deck",
  description: "A practical deck covering reconnaissance, validation, reporting, and common web security issues in bug bounty workflows.",
  label: "Bug Bounty",
  shortLabel: "Bug Bounty",
  cards: [
    { term: "Scope", definition: "The systems, domains, APIs, or assets a bug bounty program explicitly allows researchers to test." },
    { term: "Out of Scope", definition: "Targets or techniques that a program specifically forbids." },
    { term: "Safe Harbor", definition: "Program language that gives researchers legal comfort when they follow the rules." },
    { term: "Recon", definition: "The process of gathering information about targets before testing for vulnerabilities." },
    { term: "Subdomain Enumeration", definition: "Discovering subdomains associated with a target organization." },
    { term: "Content Discovery", definition: "Finding hidden files, directories, or endpoints on a web application." },
    { term: "Parameter Mining", definition: "Discovering undocumented parameters that may change application behavior." },
    { term: "Attack Surface Mapping", definition: "Building a picture of reachable hosts, apps, APIs, and functionality." },
    { term: "Burp Suite", definition: "A common web security platform used for interception, testing, and vulnerability research." },
    { term: "Repeater", definition: "A Burp feature used to resend and modify requests manually." },
    { term: "Intruder", definition: "A Burp feature used to automate repeated requests with varying payloads." },
    { term: "Proof of Concept", definition: "A minimal demonstration showing that a reported issue is real." },
    { term: "Impact Statement", definition: "A concise explanation of what an attacker could achieve with a vulnerability." },
    { term: "Duplicate", definition: "A report that matches a vulnerability already submitted by another researcher." },
    { term: "Informative", definition: "A report that contains useful information but does not qualify as a valid vulnerability." },
    { term: "Triage Team", definition: "The group that validates reports and decides severity or eligibility." },
    { term: "CVSS", definition: "A scoring system often used to communicate vulnerability severity." },
    { term: "IDOR", definition: "Insecure Direct Object Reference, where an attacker accesses another user's object by changing an identifier." },
    { term: "Open Redirect", definition: "A vulnerability that lets an attacker send users to an unintended external destination." },
    { term: "Host Header Injection", definition: "Manipulating the Host header to influence application logic, links, or routing." },
    { term: "SSRF", definition: "Server-Side Request Forgery, where a server is tricked into making unintended requests." },
    { term: "Business Logic Flaw", definition: "A security issue caused by abusing intended application behavior rather than a classic code bug." },
    { term: "Rate Limit Bypass", definition: "Circumventing request limits that are supposed to slow abuse or brute force." },
    { term: "Race Condition", definition: "A flaw where timing-sensitive requests create inconsistent or unauthorized outcomes." },
    { term: "Writeup Quality", definition: "How clearly a report explains reproduction steps, evidence, impact, and fix guidance." },
    { term: "Program Policy", definition: "The rules that define what testing is allowed and how researchers should behave." },
    { term: "Vulnerability Taxonomy", definition: "A way of categorizing issues by type, class, or exploitation pattern." },
    { term: "Asset Ownership", definition: "Knowing which team or product owns a target so reports reach the right people." },
    { term: "Endpoint Enumeration", definition: "Finding all reachable routes, functions, and URLs in an application." },
    { term: "API Recon", definition: "Mapping API routes, methods, schemas, and behaviors before testing them." },
    { term: "JWT Misconfiguration", definition: "A weakness in token signing, validation, or handling that can be abused." },
    { term: "CORS Misconfiguration", definition: "Improper cross-origin policy that allows unintended sites to access resources." },
    { term: "Cache Poisoning", definition: "Injecting manipulated content into a cache so later users receive attacker-controlled responses." },
    { term: "Request Smuggling", definition: "A desync flaw caused by inconsistent HTTP request parsing between components." },
    { term: "Host Discovery", definition: "Finding live hosts that belong to the target environment." },
    { term: "URL Normalization Bug", definition: "A flaw where different components interpret the same path differently." },
    { term: "Open API Spec Leak", definition: "Exposure of internal API documentation that reveals hidden routes or models." },
    { term: "Mass Assignment", definition: "Automatically binding user input to object fields without proper restriction." },
    { term: "Access Control Matrix", definition: "A model for checking which roles should be allowed to perform which actions." },
    { term: "Privilege Boundary", definition: "The line between what a lower-privileged user can do and what they should not access." },
    { term: "Session Fixation", definition: "A flaw where an attacker causes a victim to use a session ID the attacker already knows." },
    { term: "Clickjacking", definition: "Tricking a user into clicking hidden or disguised interface elements." },
    { term: "HTML Injection", definition: "Injecting attacker-controlled markup into a rendered page." },
    { term: "Blind SSRF", definition: "An SSRF where the attacker cannot directly see the response and must infer success." },
    { term: "File Upload Validation", definition: "Checks meant to prevent malicious or unexpected content from being uploaded." },
    { term: "Source Map Exposure", definition: "Leaking JavaScript source maps that reveal internal paths or readable source." },
    { term: "Subdomain Takeover", definition: "Claiming a dangling DNS record that points to an unclaimed third-party service." },
    { term: "Stored XSS", definition: "Cross-site scripting where the payload is saved by the application and served to users later." },
    { term: "Reflected XSS", definition: "Cross-site scripting where input is immediately reflected into a response." },
    { term: "Report Reproducibility", definition: "The degree to which a triager can follow your steps and observe the same issue." }
  ],
};
