window.COMMONPLACE_DECK_REGISTRY = window.COMMONPLACE_DECK_REGISTRY || {};
window.COMMONPLACE_DECK_REGISTRY.currentphase = {
  title: "Current Phase — 6/11 to 7/7",
  description: "Priority cards for the active study phase. SAL1 Path 2 Sections 7–11, COAE AI red team concepts, Huntress/EDR vocabulary, PowerShell essentials, and Python fundamentals.",
  label: "Current Phase",
  shortLabel: "Current Phase",
  cards: [
    // ── SAL1: Exploitation Basics (Section 7) ──
    { term: "Metasploit Framework", definition: "Open-source exploitation framework. Core components: msfconsole (CLI), msfvenom (payload generator), modules (exploits, payloads, auxiliaries, post). Primary tool for Section 7 of SAL1." },
    { term: "Meterpreter", definition: "Advanced Metasploit payload that runs in memory, communicates over encrypted channel, and provides a rich post-exploitation shell. Key commands: sysinfo, getuid, getsystem, hashdump, migrate." },
    { term: "getsystem", definition: "Meterpreter command that attempts privilege escalation to SYSTEM using multiple techniques (named pipe impersonation, token duplication). Used after gaining initial Meterpreter session." },
    { term: "Local Exploit Suggester", definition: "Metasploit post module (post/multi/recon/local_exploit_suggester) that checks the target for applicable local privilege escalation exploits based on OS version and patch level." },
    { term: "Payload (Metasploit)", definition: "Code delivered to the target after exploitation. Types: singles (self-contained), stagers (small loader + stage), stages (full payload loaded by stager). Meterpreter is a staged payload." },
    { term: "Reverse Shell", definition: "The compromised target connects back to the attacker's listener. Preferred over bind shells because it traverses firewalls outbound, which are typically less restricted than inbound." },
    { term: "Bind Shell", definition: "The compromised target opens a listening port; attacker connects to it. Firewalls often block inbound connections, making this less reliable than reverse shells." },
    // ── SAL1: Web Hacking (Section 8) ──
    { term: "SQL Injection", definition: "Inserting SQL syntax into input fields to manipulate backend database queries. Types: in-band (error-based, union-based), blind (boolean, time-based), out-of-band." },
    { term: "Union-Based SQLi", definition: "Uses UNION SELECT to append a second query to the original, returning data in the same response. Requires knowing the number of columns and compatible data types." },
    { term: "Blind SQLi (Boolean)", definition: "No data is returned directly. Attacker infers information by asking true/false questions and observing application behavior changes (different response, length, or redirect)." },
    { term: "Blind SQLi (Time-Based)", definition: "No visible response difference. Attacker infers data by causing the database to sleep (SLEEP(), WAITFOR DELAY) and measuring response time." },
    { term: "Burp Suite Proxy", definition: "Intercepts HTTP/S traffic between browser and server. Core workflow: set browser proxy → capture request → send to Repeater (manual testing) or Intruder (fuzzing)." },
    { term: "Burp Repeater", definition: "Burp Suite tool for manually replaying and modifying HTTP requests. Essential for iterative testing of parameter tampering, injection, and auth bypass." },
    { term: "Burp Intruder", definition: "Burp Suite tool for automated fuzzing of HTTP parameters. Attack types: Sniper (one position, one payload list), Cluster Bomb (multiple positions, multiple lists)." },
    { term: "OWASP Top 10", definition: "The ten most critical web application security risks. In 2025: Broken Access Control, Cryptographic Failures, Injection, Insecure Design, Security Misconfiguration, Vulnerable Components, Auth Failures, Data Integrity Failures, Logging Failures, SSRF." },
    { term: "Broken Access Control", definition: "OWASP #1. Users can act outside their intended permissions — accessing other users' data (IDOR), escalating privileges, or accessing admin functions without authorization." },
    { term: "SSRF (Server-Side Request Forgery)", definition: "Attacker causes the server to make HTTP requests to internal resources. Common targets: cloud metadata (169.254.169.254), internal services, other backend systems not exposed to the internet." },
    // ── SAL1: Offensive Tooling (Section 9) ──
    { term: "Hydra", definition: "Online password brute-force tool. Supports many protocols: SSH, FTP, HTTP, RDP, SMB. Syntax: hydra -l user -P wordlist.txt ssh://target. Use -L for userlist, -p for single password." },
    { term: "Gobuster", definition: "Directory and file brute-forcing tool using wordlists. Modes: dir (directory brute force), dns (subdomain enumeration), vhost (virtual host discovery). Faster than DirBuster." },
    { term: "SQLMap", definition: "Automated SQL injection detection and exploitation tool. Takes a target URL or Burp request file, fingerprints the DBMS, and can dump tables, crack hashes, or gain OS shell." },
    { term: "Gobuster dir mode", definition: "Brute-forces web directories and files. Command: gobuster dir -u http://target -w /usr/share/wordlists/dirb/common.txt -x php,html,txt. -x adds file extensions." },
    // ── SAL1: Defensive Security (Section 10) ──
    { term: "Incident Response Phases", definition: "NIST framework: Preparation → Detection & Analysis → Containment → Eradication → Recovery → Post-Incident Activity. Huntress ThreatOps operates primarily in Detection and Containment phases." },
    { term: "Containment (IR)", definition: "Limiting the spread and impact of an incident. Short-term: isolate the affected host. Long-term: patch root cause before reconnecting. Must preserve forensic evidence." },
    { term: "Eradication (IR)", definition: "Removing the threat: malware removal, account disablement, closing initial access vector. Occurs after containment is confirmed. Do not eradicate before containing." },
    { term: "Digital Forensics", definition: "The collection, preservation, and analysis of digital evidence. Key principle: never modify original evidence. Work from forensic copies. Document chain of custody." },
    { term: "Logs Fundamentals", definition: "Key log sources: Windows Event Log (Security, System, Application), Sysmon, firewall logs, web server logs, auth logs. Event IDs to know: 4624 (logon), 4625 (failed logon), 4688 (process creation), 7045 (service install)." },
    { term: "Windows Event ID 4688", definition: "Process creation event. Records new process name, parent process, command line (if audited), and user context. Critical for detecting PowerShell abuse, LOLBins, and malware execution." },
    { term: "Windows Event ID 4625", definition: "Failed logon attempt. Logon type and failure reason are key fields. Patterns: many 4625s from one source = brute force; many accounts, one source = password spray." },
    { term: "Sysmon", definition: "Microsoft Sysinternals tool that extends Windows Event Log with detailed process, network, and file events. Event ID 1 (process create) and 3 (network connection) are the most used for detection." },
    // ── SAL1: Security Solutions (Section 11) ──
    { term: "SIEM", definition: "Security Information and Event Management. Aggregates logs from across the environment, correlates events into alerts, and provides search and dashboard capability. Examples: Splunk, Elastic, Microsoft Sentinel." },
    { term: "IDS vs IPS", definition: "Intrusion Detection System detects and alerts. Intrusion Prevention System detects and blocks. IDS is passive (monitor only); IPS is inline (can drop traffic). Both can be network-based (NIDS/NIPS) or host-based." },
    { term: "Snort", definition: "Open-source network IDS/IPS. Uses rules to match packet content and headers. Rule syntax: action protocol src_ip src_port direction dst_ip dst_port (options). Alert = log and notify; drop = block in IPS mode." },
    { term: "Firewall Rule Evaluation", definition: "Rules are evaluated top to bottom; first match wins. Most firewalls have an implicit deny-all at the bottom. Stateful firewalls track connection state — return traffic is automatically allowed." },
    { term: "Vulnerability Scanner", definition: "Tool that probes systems for known vulnerabilities without exploiting them. Examples: Nessus, OpenVAS. Outputs severity-rated findings (CVSS score). Distinct from exploitation tools like Metasploit." },
    // ── COAE Priority Concepts ──
    { term: "Direct vs Indirect Prompt Injection", definition: "Direct: attacker inputs malicious prompt through the user interface. Indirect: malicious instructions embedded in external content the model retrieves (documents, web pages, tool output) — the attacker isn't in the conversation." },
    { term: "Output-Based Exploitation", definition: "LLM output becomes application input. The model is the injection vector, not the final target. Attack surfaces: web renderer (XSS), database query (SQLi), command execution (RCE), API calls." },
    { term: "AI Pipeline Weak Points", definition: "The infrastructure around the model is usually more exploitable than the model itself: input preprocessing, inference API, output handling, orchestration layer, logging, storage." },
    { term: "Data Poisoning", definition: "Corrupting training data to cause model misbehavior. Types: label flipping (swap correct labels), clean-label (correct labels, adversarial inputs), trojan insertion (backdoor trigger)." },
    { term: "Membership Inference", definition: "Querying a model to determine whether a specific record was in its training data. Enabled by overfitting — the model behaves differently on data it was trained on vs unseen data." },
    { term: "Anomaly Types (AI Security)", definition: "Point anomaly: one outlier data point. Contextual anomaly: normal value, wrong situation. Collective anomaly: individually normal actions that form a suspicious pattern together (e.g., distributed password spray)." },
    // ── Huntress / EDR ──
    { term: "LOLRMM", definition: "Living Off the Land RMM — using signed, trusted RMM binaries (ScreenConnect, AnyDesk, Atera) for persistent attacker access. EDR whitelists them by default; behavior monitoring is required to detect abuse." },
    { term: "Daisy-Chaining", definition: "Installing multiple RMMs sequentially for redundant persistence. Analyst finds ScreenConnect (trusted), misses Tiflux running underneath. Finding two or more RMMs simultaneously = incident, not IT redundancy." },
    { term: "Behavioral vs Signature Detection", definition: "Signature: match against known-bad hashes/patterns. Behavioral: what does the process do? Behavioral catches LOLBins and signed malware that signature misses. Huntress ThreatOps adds human review on top of both." },
    { term: "ITDR", definition: "Identity Threat Detection and Response. Detects attacks against identity: Kerberoasting, pass-the-hash, Golden Ticket, account takeover, MFA bypass. Identity is the primary attack vector in MSP environments." },
    // ── PowerShell ──
    { term: "PowerShell Pipeline", definition: "Passes objects (not text) between cmdlets using |. Each cmdlet receives the full object with all properties. Example: Get-Process | Where-Object CPU -gt 100 | Select-Object Name, CPU" },
    { term: "Get-Help", definition: "Primary PowerShell documentation cmdlet. Get-Help Get-Process -Full shows all parameters. Get-Help Get-Process -Examples shows usage examples. Always start here for unfamiliar cmdlets." },
    { term: "Where-Object", definition: "Filters pipeline objects by a condition. Aliases: where, ?. Example: Get-Service | Where-Object Status -eq 'Running'. Script block form: Where-Object { $_.CPU -gt 100 }" },
    { term: "Select-Object", definition: "Picks specific properties from pipeline objects or limits count. Example: Get-Process | Select-Object Name, CPU -First 10. Use -ExpandProperty to get a single property's value as a string." },
    { term: "ForEach-Object", definition: "Runs a script block for each object in the pipeline. Alias: %. Current object is $_. Example: Get-ChildItem | ForEach-Object { Write-Host $_.Name }" },
    { term: "PowerShell Execution Policy", definition: "Controls which scripts can run. Levels: Restricted (no scripts), RemoteSigned (local scripts OK, remote must be signed), Unrestricted (all scripts). Set per scope: Process, CurrentUser, LocalMachine." },
    { term: "Invoke-Expression (iex)", definition: "Executes a string as a PowerShell command. High-risk: attackers use iex to execute downloaded code. iex (New-Object Net.WebClient).DownloadString('http://...') is a common download-and-execute pattern." },
    { term: "$_ (Pipeline Variable)", definition: "Represents the current object in a pipeline script block. Used inside Where-Object, ForEach-Object, and similar cmdlets. Example: Get-Process | ForEach-Object { $_.Name }" },
    // ── Python ──
    { term: "Python List vs Dictionary", definition: "List: ordered, indexed by integer, allows duplicates. my_list[0]. Dict: key-value pairs, indexed by key, keys unique. my_dict['key']. Lists use [], dicts use {}." },
    { term: "Python f-string", definition: "Formatted string literal. Embeds expressions in strings: f'Hello {name}, you have {count} items'. Evaluated at runtime. Cleaner than .format() or % formatting." },
    { term: "Python try/except", definition: "Error handling block. try: code that might fail. except ExceptionType as e: handle it. finally: always runs. Use specific exception types (ValueError, FileNotFoundError) not bare except." },
    { term: "Python with statement", definition: "Context manager — automatically handles setup and teardown. with open('file.txt', 'r') as f: data = f.read(). File is closed automatically even if an exception occurs." },
    { term: "Python requests library", definition: "HTTP client library. r = requests.get(url, headers={}, params={}). Check r.status_code, r.json(), r.text. Use r.raise_for_status() to throw on 4xx/5xx responses." },
    { term: "Python list comprehension", definition: "Concise way to create lists. [expression for item in iterable if condition]. Example: [x*2 for x in range(10) if x % 2 == 0]. Equivalent to a for loop with append." },
  ],
};
