window.COMMONPLACE_DECK_REGISTRY = window.COMMONPLACE_DECK_REGISTRY || {};
window.COMMONPLACE_DECK_REGISTRY.cybersecurity = {
  title: "Cybersecurity Vocabulary Deck",
  description: "A broad essentials deck covering entry-level analyst terms, common attack concepts, and core defensive language.",
  label: "Security Essentials",
  shortLabel: "Cybersecurity Essentials",
  cards: [
    { term: "CIA Triad", definition: "The principle that security work protects confidentiality, integrity, and availability." },
    { term: "Least Privilege", definition: "Giving a user or system only the permissions needed to perform its task and nothing more." },
    { term: "MFA", definition: "Multi-factor authentication, which requires more than one proof of identity such as a password and a code." },
    { term: "Phishing", definition: "A social engineering attack that tricks someone into revealing credentials, money, or sensitive data." },
    { term: "Spear Phishing", definition: "A targeted phishing attempt crafted for a specific person, role, or organization." },
    { term: "Malware", definition: "Malicious software such as ransomware, spyware, trojans, or worms designed to harm or exploit systems." },
    { term: "Ransomware", definition: "Malware that encrypts or locks data and demands payment to restore access." },
    { term: "Hash", definition: "A fixed-length output created from data, often used for password storage, integrity checks, and forensics." },
    { term: "SIEM", definition: "Security Information and Event Management, a platform that collects, correlates, and analyzes logs and alerts." },
    { term: "IOC", definition: "Indicator of compromise, a forensic clue such as a malicious IP, hash, domain, or file path tied to an intrusion." },
    { term: "TTPs", definition: "Tactics, techniques, and procedures describing how an adversary behaves and carries out operations." },
    { term: "Zero Trust", definition: "A security model that assumes no implicit trust and continuously verifies users, devices, and access requests." },
    { term: "Vulnerability", definition: "A weakness in software, hardware, process, or configuration that could be exploited." },
    { term: "Exploit", definition: "Code or action that takes advantage of a vulnerability to gain unauthorized access or execution." },
    { term: "Patch Management", definition: "The process of identifying, testing, and deploying updates that fix vulnerabilities and bugs." },
    { term: "EDR", definition: "Endpoint Detection and Response, tooling that monitors devices for suspicious behavior and supports investigation." },
    { term: "IDS", definition: "Intrusion Detection System, a tool that monitors traffic or systems and alerts on suspicious activity." },
    { term: "IPS", definition: "Intrusion Prevention System, a control that can actively block or stop malicious traffic in real time." },
    { term: "Firewall", definition: "A network security control that filters traffic based on rules such as IPs, ports, protocols, or applications." },
    { term: "VPN", definition: "Virtual Private Network, an encrypted tunnel used to securely access a remote network." },
    { term: "DLP", definition: "Data Loss Prevention, controls that detect and prevent sensitive data from leaving authorized boundaries." },
    { term: "Incident Response", definition: "The organized process for identifying, containing, eradicating, and recovering from a security incident." },
    { term: "Lateral Movement", definition: "An attacker moving from one compromised system to other systems inside the environment." },
    { term: "Exfiltration", definition: "The unauthorized transfer of data out of an organization, system, or secured environment." },
    { term: "Authentication", definition: "The process of verifying that a user, device, or service is who it claims to be." },
    { term: "Authorization", definition: "The process of deciding what an authenticated identity is allowed to do." },
    { term: "Attack Surface", definition: "The total set of systems, services, paths, and exposures that an attacker could target." },
    { term: "Threat Actor", definition: "A person, group, or organization that carries out malicious activity." },
    { term: "Threat Intelligence", definition: "Collected and analyzed information about adversaries, indicators, and emerging risks." },
    { term: "Threat Hunting", definition: "Proactively searching an environment for signs of malicious activity that alerts may have missed." },
    { term: "Risk", definition: "The potential impact and likelihood of a threat exploiting a vulnerability." },
    { term: "Mitigation", definition: "An action or control that reduces the likelihood or impact of a security risk." },
    { term: "Defense in Depth", definition: "Layering multiple controls so one failure does not expose the entire environment." },
    { term: "Hardening", definition: "Reducing attack surface by disabling unnecessary services, tightening settings, and applying secure defaults." },
    { term: "Secure Baseline", definition: "A defined starting point of approved settings used to keep systems consistently hardened." },
    { term: "Asset Inventory", definition: "A maintained record of devices, software, accounts, and services in an environment." },
    { term: "False Positive", definition: "An alert that incorrectly signals malicious activity when no real threat is present." },
    { term: "Triage", definition: "The process of quickly reviewing and prioritizing alerts or incidents for investigation." },
    { term: "Containment", definition: "Actions taken to limit the spread or impact of an incident after it is identified." },
    { term: "Eradication", definition: "Removing the root cause of an intrusion such as malware, persistence, or compromised accounts." },
    { term: "Recovery", definition: "Restoring systems and operations to a trusted and functioning state after an incident." },
    { term: "SOAR", definition: "Security Orchestration, Automation, and Response, used to automate and coordinate security workflows." },
    { term: "Log Source", definition: "A system or application that produces logs for monitoring and investigation." },
    { term: "Event Log", definition: "A record of system or application activity that can be reviewed for troubleshooting or detection." },
    { term: "Syslog", definition: "A standard logging format and transport commonly used by network devices and Unix-like systems." },
    { term: "Windows Event ID", definition: "A numeric identifier assigned to a Windows log event to describe a specific action or condition." },
    { term: "Telemetry", definition: "Operational and security data collected from endpoints, networks, or cloud services." },
    { term: "Correlation Rule", definition: "Logic in a SIEM that links related events together to identify suspicious behavior." },
    { term: "Detection Engineering", definition: "Designing, testing, and maintaining detections that identify malicious activity reliably." },
    { term: "Signature-Based Detection", definition: "Detection that relies on known patterns such as hashes, strings, or rule matches." },
    { term: "Behavior-Based Detection", definition: "Detection that looks for suspicious actions or sequences rather than exact known signatures." },
    { term: "YARA", definition: "A rule language often used to identify malware families or suspicious files based on content patterns." },
    { term: "Sigma", definition: "A generic rule format for describing detections that can be translated across SIEM platforms." },
    { term: "MITRE ATT&CK", definition: "A knowledge base that maps adversary tactics and techniques observed in real-world operations." },
    { term: "Kill Chain", definition: "A model describing phases of an intrusion from reconnaissance through actions on objectives." },
    { term: "Reconnaissance", definition: "Gathering information about a target before attempting exploitation or intrusion." },
    { term: "Command and Control", definition: "A communication channel used by attackers to remotely control compromised systems." },
    { term: "Beaconing", definition: "A recurring outbound connection from malware to its command infrastructure." },
    { term: "Persistence", definition: "A method attackers use to maintain access across reboots, logouts, or other interruptions." },
    { term: "Privilege Escalation", definition: "Gaining higher permissions than initially granted, such as moving from user to admin." },
    { term: "Credential Dumping", definition: "Extracting passwords, hashes, or authentication secrets from a compromised system." },
    { term: "Pass-the-Hash", definition: "Using a stolen password hash to authenticate without knowing the actual plaintext password." },
    { term: "Pass-the-Ticket", definition: "Using a stolen Kerberos ticket to impersonate a user or service." },
    { term: "Kerberoasting", definition: "Requesting Kerberos service tickets and attempting to crack them offline to recover service account passwords." },
    { term: "NTLM", definition: "An older Windows authentication protocol still commonly seen in enterprise environments." },
    { term: "Kerberos", definition: "A network authentication protocol that uses tickets for verifying identities securely." },
    { term: "Active Directory", definition: "Microsoft's directory service used to manage users, computers, groups, and domain authentication." },
    { term: "Domain Controller", definition: "A server that handles authentication, authorization, and directory operations in an Active Directory domain." },
    { term: "Group Policy", definition: "A Windows management feature used to enforce configuration and security settings across systems." },
    { term: "Service Account", definition: "An account used by applications or services rather than by human users." },
    { term: "SMB", definition: "Server Message Block, a protocol used for file sharing, printers, and some remote administration." },
    { term: "RDP", definition: "Remote Desktop Protocol, used to access Windows systems graphically over a network." },
    { term: "SSH", definition: "Secure Shell, used to securely manage systems over a network command line." },
    { term: "DNS", definition: "Domain Name System, which translates human-readable names into IP addresses." },
    { term: "DHCP", definition: "Dynamic Host Configuration Protocol, which automatically assigns IP settings to devices." },
    { term: "Egress Filtering", definition: "Restricting outbound network traffic so systems can communicate only with approved destinations or services." },
    { term: "Email Authentication", definition: "Using controls such as SPF, DKIM, and DMARC to reduce spoofing and phishing abuse." },
    { term: "Network Segregation", definition: "Separating systems and traffic paths to reduce unnecessary communication and attack spread." },
    { term: "Subnet", definition: "A segmented portion of an IP network used for organization, performance, or security." },
    { term: "Segmentation", definition: "Separating networks or systems to reduce attack spread and limit access paths." },
    { term: "DMZ", definition: "A network zone that hosts public-facing services while separating them from internal systems." },
    { term: "Proxy", definition: "A server or service that forwards requests on behalf of clients or systems." },
    { term: "Packet Capture", definition: "A record of network traffic used for analysis, troubleshooting, or investigation." },
    { term: "NetFlow", definition: "Metadata about network conversations such as source, destination, protocol, and byte counts." },
    { term: "TLS", definition: "Transport Layer Security, the protocol used to encrypt many modern network connections." },
    { term: "Certificate", definition: "A digital document used to bind a public key to an identity for trust and encryption." },
    { term: "Public Key Infrastructure", definition: "The systems and processes used to issue, manage, and validate digital certificates." },
    { term: "Data Classification", definition: "Labeling information by sensitivity or importance so it can be handled appropriately." },
    { term: "PII", definition: "Personally identifiable information, such as names, addresses, or identifiers tied to a person." },
    { term: "Regulatory Compliance", definition: "Meeting legal or industry requirements such as HIPAA, PCI DSS, or GDPR." },
    { term: "Backup", definition: "A separate copy of data kept so it can be restored if the original is lost or damaged." },
    { term: "Sandbox", definition: "An isolated environment used to safely observe or test suspicious files and behavior." },
    { term: "Remote Code Execution", definition: "A vulnerability or exploit outcome where code runs on a target from a remote source." },
    { term: "SQL Injection", definition: "An attack that manipulates database queries by injecting crafted input into an application." },
    { term: "Cross-Site Scripting", definition: "A web attack where malicious scripts run in another user's browser through a vulnerable site." },
    { term: "Cross-Site Request Forgery", definition: "A web attack that tricks a logged-in user into submitting unwanted actions to an application." },
    { term: "Brute Force Attack", definition: "Repeatedly guessing passwords, keys, or values until the correct one is found." },
    { term: "Password Spray", definition: "Trying a small set of common passwords against many accounts to avoid lockouts." },
    { term: "Account Lockout", definition: "A defensive control that disables login attempts after too many failures." },
    { term: "Insider Threat", definition: "Risk posed by a trusted individual who intentionally or accidentally harms the organization." }
  ],
};
