window.COMMONPLACE_DECK_REGISTRY = window.COMMONPLACE_DECK_REGISTRY || {};
window.COMMONPLACE_DECK_REGISTRY.linux = {
  title: "Linux CLI / Bash Deck",
  description: "A practical starter deck covering common Linux terminal commands, shell concepts, file operations, and remote administration basics.",
  label: "Linux Command Line",
  shortLabel: "Linux CLI / Bash",
  cards: [
    { term: "stdin", definition: "Standard input, the default stream a command reads data from." },
    { term: "stdout", definition: "Standard output, the default stream a command writes normal results to." },
    { term: "stderr", definition: "Standard error, the stream used for error messages and diagnostics." },
    { term: "mkdir", definition: "Creates a new directory." },
    { term: "rmdir", definition: "Removes an empty directory." },
    { term: "touch", definition: "Creates an empty file or updates a file timestamp." },
    { term: "cp", definition: "Copies files or directories." },
    { term: "mv", definition: "Moves or renames files and directories." },
    { term: "rm", definition: "Removes files or directories." },
    { term: "cat", definition: "Displays the contents of a file." },
    { term: "less", definition: "Views file contents one screen at a time." },
    { term: "head", definition: "Shows the first lines of a file." },
    { term: "tail", definition: "Shows the last lines of a file." },
    { term: "grep", definition: "Searches text for lines matching a pattern." },
    { term: "find", definition: "Searches for files and directories by name, type, or other attributes." },
    { term: "locate", definition: "Finds files quickly using a prebuilt database." },
    { term: "which", definition: "Shows the path of a command that will run." },
    { term: "whereis", definition: "Locates a command's binary, source, and manual pages." },
    { term: "man", definition: "Opens the manual page for a command." },
    { term: "echo", definition: "Prints text or variable values to the terminal." },
    { term: "chmod", definition: "Changes file or directory permissions." },
    { term: "chown", definition: "Changes file or directory ownership." },
    { term: "sudo", definition: "Runs a command with elevated privileges." },
    { term: "ps", definition: "Displays information about running processes." },
    { term: "top", definition: "Shows a live view of system processes and resource usage." },
    { term: "kill", definition: "Sends a signal to stop or control a process." },
    { term: "killall", definition: "Sends a signal to processes by name." },
    { term: "df", definition: "Displays disk space usage for mounted filesystems." },
    { term: "du", definition: "Estimates file and directory disk usage." },
    { term: "free", definition: "Shows memory and swap usage." },
    { term: "uname", definition: "Displays system information such as kernel and architecture." },
    { term: "whoami", definition: "Prints the current username." },
    { term: "id", definition: "Shows user and group IDs for an account." },
    { term: "hostname", definition: "Displays or sets the system hostname." },
    { term: "xargs", definition: "Builds and runs commands using input received from standard input." },
    { term: "tee", definition: "Writes command output to both the terminal and a file at the same time." },
    { term: "nano", definition: "A simple terminal-based text editor." },
    { term: "vim", definition: "A powerful terminal-based text editor with modal editing." },
    { term: "ssh", definition: "Connects securely to a remote system over Secure Shell." },
    { term: "scp", definition: "Copies files securely between systems over SSH." },
    { term: "curl", definition: "Transfers data to or from a URL, often used with APIs and downloads." },
    { term: "wget", definition: "Downloads files from the web or network locations." },
    { term: "tar", definition: "Archives or extracts groups of files." },
    { term: "gzip", definition: "Compresses files using gzip format." },
    { term: "zip", definition: "Compresses files into ZIP archives." },
    { term: "unzip", definition: "Extracts ZIP archives." },
    { term: "pipe", definition: "The | operator, which sends one command's output into another command." },
    { term: "redirect", definition: "Using >, >>, or < to send input or output to or from files." },
    { term: "wildcard", definition: "A pattern character like * or ? used to match filenames." },
    { term: "Bash Script", definition: "A text file of shell commands executed by Bash, often used for automation." }
  ],
};
