window.COMMONPLACE_DECK_REGISTRY = window.COMMONPLACE_DECK_REGISTRY || {};
window.COMMONPLACE_DECK_REGISTRY.powershell = {
  title: "PowerShell Essentials Deck",
  description: "A practical deck covering foundational PowerShell cmdlets, objects, and concepts that are especially useful for analysts and administrators.",
  label: "PowerShell Fundamentals",
  shortLabel: "PowerShell Essentials",
  cards: [
    { term: "Splatting", definition: "Passing a collection of named parameters to a command using a hashtable or array." },
    { term: "Pipeline Input", definition: "Allowing a command or function to accept objects from the pipeline rather than only explicit arguments." },
    { term: "Get-Member", definition: "Shows the properties and methods available on an object passed through the pipeline." },
    { term: "Get-Process", definition: "Lists running processes and their details on the system." },
    { term: "Get-Service", definition: "Displays Windows services and their current status." },
    { term: "Get-EventLog", definition: "Retrieves entries from classic Windows event logs." },
    { term: "Get-WinEvent", definition: "Retrieves modern Windows event data with more flexible filtering than Get-EventLog." },
    { term: "Get-ChildItem", definition: "Lists files, folders, registry keys, or other child items in a location." },
    { term: "Get-Item", definition: "Retrieves a specific item such as a file, directory, or registry key." },
    { term: "Get-Content", definition: "Reads the contents of a file or similar data source." },
    { term: "Set-Content", definition: "Writes or replaces content in a file." },
    { term: "Add-Content", definition: "Appends additional content to an existing file." },
    { term: "Copy-Item", definition: "Copies files, folders, or other items from one location to another." },
    { term: "Move-Item", definition: "Moves an item from one path or provider location to another." },
    { term: "Remove-Item", definition: "Deletes files, folders, registry keys, or other items." },
    { term: "New-Item", definition: "Creates a new file, directory, or other provider-backed item." },
    { term: "Test-Path", definition: "Checks whether a path exists." },
    { term: "Select-Object", definition: "Chooses specific properties or a subset of objects from pipeline output." },
    { term: "Where-Object", definition: "Filters objects in the pipeline based on property values or expressions." },
    { term: "Sort-Object", definition: "Sorts pipeline objects by one or more properties." },
    { term: "Group-Object", definition: "Groups objects that share the same property value." },
    { term: "Measure-Object", definition: "Calculates counts, sums, averages, and other measurements on objects." },
    { term: "ForEach-Object", definition: "Performs an action on each object passed through the pipeline." },
    { term: "Out-File", definition: "Sends command output to a file." },
    { term: "Export-Csv", definition: "Writes objects to a CSV file while preserving structured properties." },
    { term: "Import-Csv", definition: "Reads CSV data into PowerShell objects." },
    { term: "ConvertTo-Json", definition: "Converts PowerShell objects into JSON text." },
    { term: "ConvertFrom-Json", definition: "Converts JSON text into PowerShell objects." },
    { term: "Select-String", definition: "Searches text using patterns, similar to grep." },
    { term: "Get-Date", definition: "Displays the current date and time or creates date objects." },
    { term: "Start-Process", definition: "Launches a process or application." },
    { term: "Stop-Process", definition: "Terminates one or more running processes." },
    { term: "Get-NetTCPConnection", definition: "Lists TCP connections and listeners on Windows systems." },
    { term: "Resolve-DnsName", definition: "Performs DNS lookups from PowerShell." },
    { term: "Get-LocalUser", definition: "Lists local user accounts on a Windows system." },
    { term: "Get-LocalGroupMember", definition: "Shows which accounts belong to a local group such as Administrators." },
    { term: "Invoke-Command", definition: "Runs commands locally or remotely, often used for remoting and administration." },
    { term: "Invoke-WebRequest", definition: "Sends HTTP or HTTPS requests and returns web response data." },
    { term: "Invoke-RestMethod", definition: "Calls REST APIs and automatically parses structured response data." },
    { term: "Get-ExecutionPolicy", definition: "Displays the current PowerShell execution policy configuration." },
    { term: "Set-ExecutionPolicy", definition: "Changes how PowerShell handles script execution on the system." },
    { term: "Get-Module", definition: "Lists PowerShell modules that are loaded or available." },
    { term: "Import-Module", definition: "Loads a module so its commands are available in the session." },
    { term: "PSCustomObject", definition: "A convenient custom object type used to build structured output in scripts." },
    { term: "Pipeline", definition: "The mechanism that passes objects from one command to the next using the pipe symbol." },
    { term: "Parameter Set", definition: "A way of defining valid combinations of parameters for a command or function." },
    { term: "Script Block", definition: "A reusable block of PowerShell code enclosed in curly braces." },
    { term: "Advanced Function", definition: "A function that behaves like a cmdlet and supports common PowerShell features such as parameter binding." },
    { term: "Format-Table", definition: "A formatting command used to display selected object properties in a table view." },
    { term: "Hashtable", definition: "A key-value collection commonly used for quick lookups or structured parameters." }
  ],
};
