window.COMMONPLACE_DECK_REGISTRY = window.COMMONPLACE_DECK_REGISTRY || {};
window.COMMONPLACE_DECK_REGISTRY.python = {
  title: "Python 101 Deck",
  description: "A beginner-friendly deck covering the syntax, objects, control flow, functions, and error handling concepts most people need early in Python.",
  label: "Python Fundamentals",
  shortLabel: "Python 101",
  cards: [
    { term: "Variable", definition: "A named reference to a value, typically created with assignment like x = 10." },
    { term: "Mutability", definition: "Whether an object can be changed in place after it is created." },
    { term: "List Slicing", definition: "Using start:stop:step syntax to select ranges from a sequence." },
    { term: "Keyword Argument", definition: "Passing a value to a function by parameter name instead of only by position." },
    { term: "Default Argument", definition: "A function parameter value that is used automatically when no argument is provided." },
    { term: "None", definition: "Python's special value for no value or absence of data." },
    { term: "List", definition: "An ordered, mutable collection written with square brackets." },
    { term: "Tuple", definition: "An ordered, immutable collection written with parentheses." },
    { term: "Dictionary", definition: "A key-value collection written with curly braces." },
    { term: "Set", definition: "An unordered collection of unique values, often used for membership tests and deduplication." },
    { term: "Index", definition: "A position in a sequence, starting at zero." },
    { term: "Slice", definition: "A way to select a range from a sequence with start:stop:step." },
    { term: "for Loop", definition: "A loop that iterates through each item in an iterable." },
    { term: "while Loop", definition: "A loop that repeats while a condition stays true." },
    { term: "if Statement", definition: "A conditional branch used to run code only when a condition is true." },
    { term: "elif", definition: "An additional conditional branch checked after an if statement." },
    { term: "else", definition: "The fallback branch that runs if earlier conditions were false." },
    { term: "Function", definition: "A reusable block of code defined with def." },
    { term: "Parameter", definition: "A named input listed in a function definition." },
    { term: "Argument", definition: "An actual value passed into a function call." },
    { term: "Return", definition: "The statement used to send a value back from a function." },
    { term: "Scope", definition: "The region of code where a variable name is available." },
    { term: "Global Variable", definition: "A variable defined outside functions and accessible more broadly." },
    { term: "Local Variable", definition: "A variable created inside a function and available only there." },
    { term: "Class", definition: "A blueprint for creating objects with data and behavior." },
    { term: "Object", definition: "An instance of a class." },
    { term: "Method", definition: "A function defined inside a class and called on an object." },
    { term: "Attribute", definition: "A value stored on an object." },
    { term: "__init__", definition: "A special initializer method that runs when an object is created." },
    { term: "Module", definition: "A Python file that contains reusable code." },
    { term: "Package", definition: "A collection of related Python modules." },
    { term: "Import", definition: "The statement used to bring code from another module into the current file." },
    { term: "Exception", definition: "An error condition that can interrupt normal program flow." },
    { term: "try", definition: "Starts a block of code that may raise an exception." },
    { term: "except", definition: "Handles an exception raised in a matching try block." },
    { term: "finally", definition: "Runs cleanup code whether or not an exception occurred." },
    { term: "Syntax Error", definition: "An error caused by invalid Python grammar or structure." },
    { term: "TypeError", definition: "An error raised when an operation is used with the wrong kind of value." },
    { term: "ValueError", definition: "An error raised when the value is the right type but inappropriate." },
    { term: "Indentation", definition: "Leading whitespace that defines code blocks in Python." },
    { term: "with Statement", definition: "A construct that manages setup and cleanup automatically, often used with files and resources." },
    { term: "Docstring", definition: "A triple-quoted string used to document a module, function, or class." },
    { term: "List Comprehension", definition: "A compact way to build a list from another iterable." },
    { term: "Lambda", definition: "A small anonymous function written with the lambda keyword." },
    { term: "Iterable", definition: "An object you can loop over, such as a list, tuple, or string." },
    { term: "Iterator", definition: "An object that yields items one at a time, often via next()." },
    { term: "f-string", definition: "A string literal prefixed with f that supports inline expression formatting." },
    { term: "Virtual Environment", definition: "An isolated Python environment for project-specific packages." },
    { term: "pip", definition: "Python's package installer used to add and manage libraries." },
    { term: "__name__", definition: "A special variable used to tell whether a file is being run directly or imported." }
  ],
};
