window.COMMONPLACE_DECK_REGISTRY = window.COMMONPLACE_DECK_REGISTRY || {};
window.COMMONPLACE_DECK_REGISTRY.redteam = {
  title: "Red Team Deck",
  description: "A tradecraft-focused deck covering adversary emulation, operational security, footholds, movement, and stealth concepts.",
  label: "Red Team Ops",
  shortLabel: "Red Team",
  cards: [
    { term: "Adversary Emulation", definition: "Testing defenses by reproducing the tactics and techniques of a specific threat actor." },
    { term: "Objective-Based Operation", definition: "An exercise designed around a concrete goal instead of just running techniques." },
    { term: "Initial Foothold", definition: "The first stable access gained into a target environment." },
    { term: "Staging", definition: "Preparing payloads, infrastructure, or tooling before operational use." },
    { term: "Payload Delivery", definition: "The mechanism used to place malicious code or content on a target." },
    { term: "C2 Infrastructure", definition: "Servers, domains, and channels used to manage compromised systems." },
    { term: "OPSEC", definition: "Operational security practices used to avoid detection or attribution." },
    { term: "Egress Channel", definition: "The outbound route malware or tooling uses to communicate externally." },
    { term: "Dormant Implant", definition: "A foothold that remains quiet until reactivated later." },
    { term: "Stager", definition: "A small payload that retrieves or launches a larger second-stage payload." },
    { term: "Beacon Sleep", definition: "The wait period between outbound callback attempts." },
    { term: "Process Injection", definition: "Running code inside another process to hide or blend malicious activity." },
    { term: "Token Impersonation", definition: "Using another security token to act with that identity's privileges." },
    { term: "Lateral Tool Transfer", definition: "Moving tooling to additional hosts after initial compromise." },
    { term: "Pivot Host", definition: "A compromised system used to reach otherwise inaccessible network segments." },
    { term: "Internal Recon", definition: "Gathering information from inside the target environment after compromise." },
    { term: "Credential Material", definition: "Passwords, hashes, tickets, tokens, or keys usable for access." },
    { term: "Userland Evasion", definition: "Techniques that avoid or weaken defensive hooks in user-space processes." },
    { term: "Living Off the Land Binary", definition: "A trusted system binary abused to perform malicious actions." },
    { term: "Inline Execute", definition: "Running a task in memory without spawning a new visible process chain." },
    { term: "Malleable Profile", definition: "A customizable traffic profile used to make C2 communications resemble normal protocols." },
    { term: "Exfiltration Channel", definition: "The path used to move collected data out of the environment." },
    { term: "Cleanup", definition: "Removing tooling, artifacts, and persistence after an operation or exercise." },
    { term: "Detection Mapping", definition: "Linking performed techniques to the defensive alerts and telemetry they triggered." },
    { term: "Assumed Breach", definition: "An exercise model where the operator starts as though initial access already exists." },
    { term: "Operational Objective", definition: "The mission goal that determines what access or actions matter in an exercise." },
    { term: "Target Profiling", definition: "Studying technologies, users, and infrastructure to shape an operation." },
    { term: "Infrastructure Burn", definition: "Losing the usefulness of C2 or phishing infrastructure because it was detected or blocked." },
    { term: "Fallback Channel", definition: "A secondary communication or access path used if the primary method fails." },
    { term: "Tasking", definition: "Sending instructions or jobs to an implant or operator workflow." },
    { term: "Foothold Stability", definition: "How reliable and durable a compromised access point is over time." },
    { term: "Credential Access", definition: "Activities focused on collecting or abusing authentication material." },
    { term: "User Execution", definition: "Relying on a target user to open or run something as part of the intrusion." },
    { term: "Phishing Pretext", definition: "The believable story used to increase success of a phishing attempt." },
    { term: "Persistence Trigger", definition: "The system event or condition that causes a persistence mechanism to run." },
    { term: "Stealth Tradeoff", definition: "Balancing operational speed or capability against the chance of detection." },
    { term: "Credential Relay", definition: "Forwarding captured authentication attempts to another service to gain access." },
    { term: "Session Hijack", definition: "Taking control of a valid authenticated session instead of logging in directly." },
    { term: "Collection Staging", definition: "Gathering data in one place internally before exfiltrating it." },
    { term: "EDR Bypass", definition: "A technique intended to evade endpoint protection or monitoring tools." },
    { term: "Direct System Call", definition: "Invoking lower-level calls to reduce reliance on monitored higher-level APIs." },
    { term: "Tradecraft Validation", definition: "Confirming that techniques behave as expected in a target-like environment." },
    { term: "Operator Error", definition: "A mistake by the attacker that creates extra noise, breaks OPSEC, or triggers detection." },
    { term: "Proxy Chain", definition: "A sequence of hosts or services used to route traffic indirectly." },
    { term: "Infrastructure Segregation", definition: "Separating components of an operation so one detection does not expose everything." },
    { term: "Targeted Collection", definition: "Gathering only data aligned with the operation objective instead of everything available." },
    { term: "Payload Staging Server", definition: "A host used to store and deliver payloads during an operation." },
    { term: "Lure Document", definition: "A crafted file designed to entice a target into opening malicious content." },
    { term: "Counter-Forensics", definition: "Techniques meant to reduce or obscure evidence left behind." },
    { term: "Access Loss", definition: "The point where an established foothold is no longer usable." }
  ],
};
