window.COMMONPLACE_DECK_REGISTRY = window.COMMONPLACE_DECK_REGISTRY || {};
window.COMMONPLACE_DECK_REGISTRY.soc = {
  title: "SOC Analyst Readiness Deck",
  description: "A practical readiness deck covering alert handling, investigation workflow, documentation, escalation, and common SOC operations language.",
  label: "SOC Readiness",
  shortLabel: "SOC Analyst Readiness",
  cards: [
    { term: "Alert Triage", definition: "The process of reviewing alerts quickly to decide priority, severity, and next steps." },
    { term: "Escalation", definition: "Passing an alert or incident to a more senior analyst or another team when required." },
    { term: "Case Notes", definition: "Clear written documentation of what was observed, done, and concluded during an investigation." },
    { term: "Severity", definition: "A rating that reflects the potential impact and urgency of an alert or incident." },
    { term: "Priority", definition: "A decision about how quickly a case should be handled compared with others." },
    { term: "Use Case", definition: "A defined detection or monitoring scenario a SOC wants to identify reliably." },
    { term: "Detection Rule", definition: "Logic used to identify suspicious activity from logs or telemetry." },
    { term: "Alert Suppression", definition: "Reducing noisy alerts under defined conditions so analysts can focus on meaningful activity." },
    { term: "Noise", definition: "Benign events or low-value alerts that create clutter in a monitoring workflow." },
    { term: "Whitelisting", definition: "Allowing known-good activity so it is not repeatedly flagged as suspicious." },
    { term: "Baseline Behavior", definition: "Normal system or user activity used as a reference for spotting anomalies." },
    { term: "Anomaly", definition: "Activity that deviates from expected or normal behavior." },
    { term: "Enrichment", definition: "Adding useful context to an alert, such as user, host, geo, threat intel, or asset criticality." },
    { term: "Context", definition: "Supporting information that helps an analyst interpret whether an alert matters." },
    { term: "Asset Criticality", definition: "How important a device, application, or system is to business operations." },
    { term: "User Context", definition: "Information about a user's role, department, access level, or normal behavior." },
    { term: "Timeboxing", definition: "Spending a limited amount of time on an investigation step before reassessing." },
    { term: "Pivot", definition: "Changing direction in an investigation by following a new clue such as an IP, host, or account." },
    { term: "Timeline Analysis", definition: "Reconstructing events in chronological order to understand what happened." },
    { term: "Root Cause", definition: "The underlying reason an alert or incident occurred." },
    { term: "Initial Access", definition: "The method an attacker used to first enter the environment." },
    { term: "Lateral Movement", definition: "Movement from one compromised system to others inside the environment." },
    { term: "Persistence", definition: "A method used by an attacker to keep access over time." },
    { term: "Privilege Escalation", definition: "Gaining higher permissions than originally available." },
    { term: "Containment Action", definition: "A defensive step taken to limit spread, such as isolating a host or disabling an account." },
    { term: "Host Isolation", definition: "Disconnecting an endpoint from the network while preserving investigation access if possible." },
    { term: "Account Disablement", definition: "Temporarily blocking an account to stop suspected misuse." },
    { term: "Indicator Search", definition: "Looking across logs and tools for a known IP, hash, domain, process, or filename." },
    { term: "Retrospective Search", definition: "Searching historical data to see whether suspicious activity happened before the current alert." },
    { term: "Threat Hunt Query", definition: "A search designed to proactively find suspicious behavior rather than respond to a single alert." },
    { term: "False Positive", definition: "An alert that appears suspicious but is ultimately benign." },
    { term: "True Positive", definition: "An alert that correctly identifies malicious activity." },
    { term: "False Negative", definition: "Malicious activity that occurred but was not detected." },
    { term: "Case Closure", definition: "The point where an investigation is finished and properly documented." },
    { term: "Evidence Preservation", definition: "Keeping logs, files, and artifacts intact so they remain useful for investigation or legal review." },
    { term: "Chain of Custody", definition: "A documented record showing who handled evidence and when." },
    { term: "Forensic Artifact", definition: "A piece of system data such as logs, registry keys, files, or memory traces useful in investigation." },
    { term: "Memory Analysis", definition: "Investigating RAM contents for processes, connections, malware, or credentials." },
    { term: "Disk Artifact", definition: "A file or disk-based trace left behind by system or attacker activity." },
    { term: "Authentication Log", definition: "A log showing login successes, failures, and identity-related events." },
    { term: "Process Tree", definition: "A view showing parent and child processes to help understand execution chains." },
    { term: "Command Line Audit", definition: "Visibility into the exact commands run by a process or user." },
    { term: "North-South Traffic", definition: "Traffic moving in or out of the environment across network boundaries." },
    { term: "East-West Traffic", definition: "Traffic moving laterally between internal systems." },
    { term: "Beaconing", definition: "Regular repeated outbound connections that may indicate malware calling home." },
    { term: "DNS Tunneling", definition: "Abusing DNS queries and responses to hide command-and-control or data transfer." },
    { term: "Data Exfiltration", definition: "Unauthorized movement of data out of the organization." },
    { term: "Ticket Queue", definition: "The stream of alerts or cases waiting for analyst review." },
    { term: "Shift Handoff", definition: "A transfer of important case information between analysts or SOC shifts." },
    { term: "SOC Metrics", definition: "Measurements such as alert volume, mean time to detect, and mean time to respond." }
  ],
};
